#!/bin/sh

git bundle create RVDEVREPLACE_projectdir/backup/RVDEVREPLACE_prefix-project-backup.pack --all
open RVDEVREPLACE_projectdir
open "https://drive.google.com/" # RVDEV: Add path to GDrive folder
