#!/bin/zsh

changed_files=`git diff --name-only "${(q)RVDEVREPLACE_PREFIX_GIT_BASE}" HEAD | rg 'ts$'`

echo "Eslint: Files changed from ${(q)RVDEVREPLACE_PREFIX_GIT_BASE}:\n${(q)changed_files}"

xargs ./node_modules/.bin/eslint --fix <<< "${(q)changed_files}"
