#!/bin/zsh

source RVDEVREPLACE_projectdir/variables/git-variables.sh

changed_files=`git diff --name-only "${(q)RVDEVREPLACE_prefix_git_base}" HEAD | rg 'ts$'`

echo "Eslint: Files changed from ${(q)RVDEVREPLACE_prefix_git_base}:\n${(q)changed_files}"

xargs ./node_modules/.bin/eslint --fix <<< "${(q)changed_files}"
